/**
 * URL and Host resolution utilities for Production Vercel QR Verification
 */

export const PRODUCTION_VERCEL_URL = 'https://iste-easwari-student-chapter-melx.vercel.app'

/**
 * Resolves the application base URL for generating phone-scannable QR verification URLs.
 *
 * Precedence:
 * 1. Configured environment override: `import.meta.env.VITE_APP_BASE_URL`
 * 2. Active browser origin if on a production HTTPS domain (e.g. Vercel deployment or custom domain)
 * 3. Default fallback: `PRODUCTION_VERCEL_URL` (https://iste-easwari-student-chapter-melx.vercel.app)
 *
 * Guarantees that the QR code generated by the deployed application and by default
 * points directly to the HTTPS Vercel production domain, NEVER localhost, 127.0.0.1, or LAN IPs.
 */
export function getAppBaseUrl(): string {
  // 1. Explicit override from environment variable (e.g. VITE_APP_BASE_URL)
  const envUrl =
    (typeof import.meta !== 'undefined' && import.meta.env?.VITE_APP_BASE_URL) ||
    (typeof process !== 'undefined' && process.env?.VITE_APP_BASE_URL)

  if (typeof envUrl === 'string' && envUrl.trim().length > 0) {
    return envUrl.trim().replace(/\/+$/, '')
  }

  // 2. If running in a browser
  if (typeof window !== 'undefined') {
    const origin = window.location.origin
    const hostname = window.location.hostname

    // Check if running on localhost or a private LAN IP
    const isLocalhostOrLan =
      hostname === 'localhost' ||
      hostname === '127.0.0.1' ||
      hostname === '::1' ||
      hostname === '0.0.0.0' ||
      hostname.startsWith('192.168.') ||
      hostname.startsWith('10.') ||
      hostname.startsWith('172.16.') ||
      hostname.startsWith('172.31.')

    // If already running on production HTTPS (e.g. Vercel or custom domain), use active origin
    if (!isLocalhostOrLan && origin.startsWith('https://')) {
      return origin.replace(/\/+$/, '')
    }
  }

  // 3. Guaranteed Production Vercel URL fallback
  return PRODUCTION_VERCEL_URL
}

/**
 * Generates the full public verification URL for a member.
 * Emits development console logs to easily verify the encoded target.
 */
export function getMemberVerificationUrl(memberIdOrCode: string): string {
  const base = getAppBaseUrl()
  const cleanId = (memberIdOrCode || '').trim()
  const verificationUrl = `${base}/verify/${encodeURIComponent(cleanId)}`

  if (typeof import.meta !== 'undefined' && import.meta.env?.DEV) {
    console.log(`[QR] Generated verification URL: ${verificationUrl}`)
  }

  return verificationUrl
}
